site_name: .fmbot
site_url: https://fm.bot/
repo_url: https://github.com/fmbot-discord/fmbot
repo_name: fmbot
site_description: Welcome to .fmbot! .fmbot is a social Discord bot that provides music statistics for you, your friends, and your fellow server members.
theme:
  name: 'material'
  custom_dir: docs/overrides
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: img/logo.png
  favicon: img/favicon.png
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - toc:
      permalink: true

extra_css:
  - style/style.css

exclude_docs: |
  !.well-known

edit_uri: ""

extra:
  analytics:
    provider: google
    property: G-2NVJXMTT2N
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fmbotDiscord
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/fm.bot/
copyright: .fmbot is not affiliated with Last.fm

nav:
  - 'Home': 'index.md'
  - 'Frequently Asked Questions': 'faq.md'
  - 'Text Commands':
    - 'Getting started': 'commands/index.md'
    - 'Albums': 'commands/albums.md'
    - 'Artists': 'commands/artists.md'
    - 'Countries': 'commands/countries.md'
    - 'Crowns': 'commands/crowns.md'
    - 'Featured': 'commands/featured.md'
    - 'Friends': 'commands/friends.md'
    - 'Genres': 'commands/genres.md'
    - 'Plays': 'commands/plays.md'
    - 'Tracks': 'commands/tracks.md'
    - 'Games': 'commands/games.md'
    - 'Discogs': 'commands/discogs.md'
    - 'Genius': 'commands/genius.md'
    - 'Apple Music': 'commands/applemusic.md'
    - 'Spotify': 'commands/spotify.md'
    - 'YouTube': 'commands/youtube.md'
    - 'Updating': 'commands/updating.md'
    - 'Miscellaneous': 'commands/misc.md'
  - 'Server configuration':
    - 'General': 'guildsettings/index.md'
    - 'WhoKnows': 'guildsettings/whoknowsettings.md'
    - 'Crowns': 'guildsettings/crownsettings.md'
    - 'Webhooks': 'guildsettings/webhooks.md'
  - 'Spotify & Apple Music importing': 'importing.md'
  - 'Music bot scrobbling': 'botscrobbling.md'
  - 'Privacy': 'privacy.md'
  - 'Terms of Use': 'terms.md'
  - 'Get supporter': 'supporter.md'
  - 'Join our server': https://discord.gg/fmbot
  - 'Add to server': https://discord.com/oauth2/authorize?client_id=356268235697553409&permissions=275415092288&scope=applications.commands%20bot
  - 'Add user app': https://discord.com/oauth2/authorize?client_id=356268235697553409&scope=applications.commands&integration_type=1
